const appname = "eMart Seller App",
    login = "Login",
    welcome = "Hi, Welcome to",
    email = "Email",
    password = "Password",
    forgotPassword = "Forgot Password?",
    emailHint = "eg. vendor@gmail.com",
    passwordHint = " * * * * * *",
    dashboard = "Dashboard",
    orders = "Orders",
    products = "Products",
    setting = "Settings",
    loginTo = "Login to your account",
    rating = "Rating",
    totalSales = "Total Sales",
    popular = "Popular Products",
    unpaid = "Unpaid",
    shopSetting = "Shop Setting",
    logout = "Logout",
    changeImage = " Change Image",
    message = "Message",
    editProfile = "Edit Profile",
    featured = "Featured",
    edit = "Edit",
    remove = "Remove",
    save = "Save",
    name ="Username",
    chat = "Chats",
    confirmPass = "Confirm Password",
    anyProblem = "In case of any difficulty, contact administration",
    credit = "@Muhammad Kamran";


//Shop Setting hint

   const nameHint = "eg. Vendor Name",
         shopDescHint = "Enter your shop description",
         shopWebsiteHint = "eg. vender.eMart.com",
         shopMobileHint = "eg. +92476374445",
         shopAddressHint = "eg Punjab Society",
         description = "Description",
         mobile = "Shop Mobile",
         website = "Shop Website",
         shopName = "Shop Name",
         address = "Shop Address";
